### ISSUE TITLE
Repository does not have a licence

### ISSUE THREAD

**Issue by McSherry** [quartiq/fastino#7]
There is no licence file for this repository and no licence specified in a header in each `.py` file, which means that by default there are no rights granted (other than the ones in [GitHub's terms][1]). This is an issue for making legal use of and modifications to the design.

Could a `LICENSE` file or similar be added?

[1]: https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#5-license-grant-to-other-users

**Comment by jordens** [comment]
Done.

It would also be great to hear from the commercial users downstream how they intend to operate regarding theses licenses. So far they all seem to be either unaware or silent.
